services:
  app:
    image: node:slim
    container_name: app
    working_dir: /src
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - RIOT_API_KEY=${RIOT_API_KEY}
    env_file:
      - .env
    tty: true
    stdin_open: true
