name = "lol-teacher"
main = "src/.output/server/index.mjs"
compatibility_date = "2025-08-17"

[env.production]
name = "lol-teacher"

[[env.production.d1_databases]]
binding = "LOGS_DB"
database_name = "lol-teacher-logs"
database_id = "YOUR_D1_DATABASE_ID"

[env.development] 
name = "lol-teacher-dev"
# 開発環境ではローカルSQLiteを使用（D1設定なし）

# Node.js compat
node_compat = true

# Build settings
[build]
command = "cd src && npm install && npm run build"
cwd = "."
watch_dir = "src"

# Assets serving configuration - Nuxtのミドルウェアで処理
# (wrangler.tomlでのassets設定は新バージョンで変更されたため無効化)
